version: '2'

services:

  db:
    image: 'postgres'
    container_name: postgresdb
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    expose:
      - 5432
    ports:
      - 5431:5432

  app:
    image: 'andy616/springboot-test:latest'
    container_name: spring-boot-app
    expose:
      - 8080
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/users
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

#volumes:
#  postgres-data: